- name: find ssl expiration dates
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: certbot | get cert expiration date
      shell: "openssl x509 -in /home/ubuntu/nginx/letsencrypt/live/{{certbot_domain}}/cert.pem -noout -enddate | cut -d= -f 2"
      register: certbot_expiration_date
      changed_when: False
