- name: find cerfication files & expiration dates
  hosts: all
  gather_facts: false

  tasks:
    - name: certbot | get cert expiration date
      shell: "date --date=\"$(openssl x509 -in /home/ubuntu/nginx/letsencrypt/live/{{certbot_domain}}/cert.pem -noout -enddate | cut -d= -f 2)\" --iso-8601"
      register: certbot_expiration_date
      changed_when: False
      when: certbot_certificate.stat.exists == True
